name: Run weibo-gh-issues

on:
  schedule:
    - cron: '0 10,22 * * *'
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install requirements
      run: |
        pip install -r requirements.txt
    - name: Run gh-issues
      env:
        WEIBO_UID: ${{ vars.WEIBO_UID }}
        WEIBO_COOKIES: ${{ vars.WEIBO_COOKIES }}
        WEIBO_LATEST_TIMESTAMP: ${{ vars.WEIBO_LATEST_TIMESTAMP }}
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        python run.py
